### ISSUE TITLE
Grammar definitions

### ISSUE THREAD

**Issue by vanhauser-thc** [atnwalk/testbed#4]
Comparing grammar mutators against each other is difficult because edge coverage is not a good indicator so usually number of different crashes found is used. What metric are you using in this testbed?

A success factor is also the grammar used. They should be the same for all mutators (and account for their different format obviously) as otherwise the differences might have a larger impact on the result than the grammar mutator itself. Did you take this into account?

Thanks!

**Comment by voidptr127** [comment]
> Comparing grammar mutators against each other is difficult because edge coverage is not a good indicator so usually number of different crashes found is used. What metric are you using in this testbed?

**Short answer:** 
All AFL++ metrics, GCOV/LCOV results, crashes, and (for confirmation) randomly selected input files. We did not introduce any new metrics in this testbed. Crashes must be manually deduplicated (see long answer).

<details>
<summary><b>Long answer</b></summary>

You are right that comparing different grammar mutators is difficult, because there is not a single metric that can be used. When we compared ATNwalk with Nautilus and Gramatron we did this mostly exploratory, i.e., by looking at the metrics we had and spotting differences. These metrics were..

Metrics from AFL++ (+Nautilus) (with `start_stats.bash`):
- Edge coverage
- Mean number of bits covered (bitmap coverage)
- Number of executions
- Number of files in the corpus

Metrics from GCOV (with `coverage_{atnwalk,nautilus,gramatron}.bash`):
- Branches covered
- Functions covered
- Files covered
- LCOV code coverage report (also includes execs per line)

Crashes (with `crash_analysis_env.bash`):
We performed post-hoc bug identification. It is a simple but time-consuming procedure, which works as follows:

1. Pick a crash and observe the error message. Put all crashes with the same error in a directory.
1. Pick a crash in the subdirectory and delete as much as possible to find the root cause (if possible). Put all crashes that follow the minimized pattern into another subdirectory.
1. If crashes are still in the error-msg directory, see whether other root causes are present. Repeat step 2 with pattern adjustments until no crashes are in the error-msg directory.
1. Repeat steps 1-3 until all crashes are categorized.
1. Submit bug reports.

This procedure was mostly scripted. I.e., when we filtered a crash according to an error message or input pattern, this was saved to a script file (`~/.filter_history`) and then reapplied to all crashes for each fuzzer. Since file names are distinguishable, we could backtrack how many crashes per campaign per fuzzer were found.

Input files:
Lastly, we also looked at input files to confirm hypotheses regarding the mutators and looked whether we observed the expected effect.

After obtaining the metrics, we first tried to explain differences with simple explanations not related to mutators. I.e., differences in grammars (see next answer) and execution performance. For execution performance, we used execution counts, number of edges covered, and bit coverage. Since none of these explained the observed difference in the metrics, we proceeded to explain differences with mutators.

We would've liked to have statistics regarding mutators and resulting parse trees, but this is hardly possible with ATNwalk without introducing significant overhead. Mainly, because mutations (havoc) to encoded files may:

1. Delete parse tree nodes or subtrees
1. Rearrange parse tree nodes or subtrees
1. Change children of parse tree nodes
1. Change terminals of the parse tree

In fact, chances are that, when you mutate a bit sequence with ATNwalk, all or a subset of the above may happen. Splicing additionally mixes all or a subset of nodes of another parse tree into this. This setup differs from other hand-crafted mutators that, e.g., Nautilus uses. Those are easily countable.
</details>


> A success factor is also the grammar used. They should be the same for all mutators (and account for their different format obviously) as otherwise the differences might have a larger impact on the result than the grammar mutator itself. Did you take this into account?

**Short answer:**
We have written our grammars in the ANTLR4 format and transformed them into the target format for Nautilus and Gramatron. See [transform_grammar.bash](https://github.com/atnwalk/grammars/blob/trunk/.script/transform_grammar.bash). Other optimizations are infeasible.

<details>

<summary><b>Long answer</b></summary>

We did use the initial grammars from Nautilus (+SQLite3), re-wrote them into the ANTLR4 format and then transformed them with scripts into the respective target format. 

Given their difference in grammar format and the number of rules to be transformed, human error is almost guaranteed. Hence, we scripted this to ensure that they really cover the same input space and can produce (theoretically) the same inputs with [transform_grammar.bash](https://github.com/atnwalk/grammars/blob/trunk/.script/transform_grammar.bash) . The challenging part was, that ANTRL's EBNF format can express more structure per rule than the other formats. Thus, we ended up transforming grammars from the EBNF format to an intermediate format and then to the target format.

While we are pretty sure that they can theoretically produce the same inputs, all fuzzers need to limit input generation in some way and, thus, inputs will ultimately differ. Gramatron was limited by having a stack depth. This not only limited the size but also caused that some grammar rules could not be produced anymore (increase of stack depth caused Gramatron to segfault). Nautilus has a default limitation of 1000 nodes per parse tree, which only limited the size of the parse tree but not the rules it could represent. ATNwalk solely relies on the execution timeout provided to AFL++ (no additional parameter).

There is a threat to internal validity that the transformed grammars are not optimal for the respective fuzzers. However, 1) we are not sure and have no empirical data what is an optimal grammar for ATNwalk. Hence, the original ANTLR4 grammar may also be not optimal. 2) Accounting for that is impossible without deeply knowing the internals of each fuzzer and knowing the implications a rule might have to the performance. In short, achieving that is impracticable. However, we did not observe a noticeable performance drop in our experiments.
</details>

I hope that this answers your questions :)

**Comment by vanhauser-thc** [comment]
looks like a sound approach, good!
